spring:
  jpa:
    properties:
      hibernate:
          ddl-auto: update
      show-sql: "true"

security:
  basic:
    enabled: false


server:
                  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
