security:
  basic:
    enabled: false

server:
    port: 8081

spring:
  jpa:
    show-sql: true


eureka:
  instance:
    prefer-ip-address: true
    appname: USERSERVICE
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/